import threading
import typing
import uuid

from abc import ABC, abstractmethod
from collections import defaultdict
from dataclasses import dataclass
from queue import Queue

from enum import Enum, auto

# Our system models its domain through a set of events that occur in it. This defines
# the scope of our system, since every event needs to have a proper reaction somewhere
# in the system.
#
# A component in our system is an entity that reacts to an event, which might result in
# another event that the system needs to react to. We made the decision to fully
# decouple system components from each other by introducing an event bus that allows
# system components to subscribe themselves to certain types of events that they want
# to receive. For this reason, system components do not communicate with each other, but
# send events (as event messages) to the event bus, which then notifies the relevant
# system components.
#
# This file contains the core of this system by first defining domain models, then
# defining the set of events the system recognizes, then defining the event bus, and
# then defining the components. The components are defined as base classes that define
# which event types a certain component needs to handle and which events it needs to
# emit in response to them. Concrete implementations of these components are then made
# outside this core module.


# ——————————————————————————————————————————————————————————————————————————————————————
# DOMAIN MODEL DEFINITIONS
# ——————————————————————————————————————————————————————————————————————————————————————


# Domain models represent concepts that have a fixed, known set of members.
class Models:
    class OrderType(Enum):
        MARKET = auto()

    class TradeSide(Enum):
        BUY = auto()
        SELL = auto()

    # The values for record types are not auto-generated but match DataBento's schema
    # values for convenience (note that this does not create any dependencies towards
    # DataBento's schemas).
    #
    # Only OHLCV record types are defined for now because the system is not yet
    # designed to handle other record types like MBO (market by order) et cetera. These
    # can be added here when the system is extended to support them.
    class RecordType(Enum):
        OHLCV_1S = 32
        OHLCV_1M = 33
        OHLCV_1H = 34
        OHLCV_1D = 35


# ——————————————————————————————————————————————————————————————————————————————————————
# EVENT DEFINITIONS
# ——————————————————————————————————————————————————————————————————————————————————————


# We need to define the base class for events outside the `Events` namespace because
# nested classes in Python cannot reference their enclosing class by name. When the
# nested event classes are being defined, the `Events` class body is still being
# executed and the name `Events` does not exist yet, so inheriting from
# `Events.EventBase` (if we defined it there) would raise a `NameError`.
@dataclass(kw_only=True, frozen=True, slots=True)
class EventBase:
    occurred_at_ns: int
    created_at_ns: int


class Events:
    class MarketUpdate:
        @dataclass(kw_only=True, frozen=True, slots=True)
        class OHLCV(EventBase):
            symbol: str
            # `typing.Literal` restricts the record type to the OHLCV members
            # specifically, so that when other record types are added to
            # `Models.RecordType` in the future, they cannot accidentally be used with
            # this event that is only supposed to carry aggregated OHLCV bars.
            record_type: typing.Literal[
                Models.RecordType.OHLCV_1S,
                Models.RecordType.OHLCV_1M,
                Models.RecordType.OHLCV_1H,
                Models.RecordType.OHLCV_1D,
            ]
            open: int
            high: int
            low: int
            close: int
            volume: int | None = None

    class BrokerRequest:
        @dataclass(kw_only=True, frozen=True, slots=True)
        class _RequestBase(EventBase):
            # The internal order ID is generated by the system before sending a request
            # to the broker. It allows us to track an order through its entire lifecycle
            # independently of whatever ID the broker assigns and keep things consistent
            # between simulated broker and live broker components.
            internal_order_id: uuid.UUID
            symbol: str

        @dataclass(kw_only=True, frozen=True, slots=True)
        class SubmitOrder(_RequestBase):
            order_type: Models.OrderType
            side: Models.TradeSide
            quantity: int
            limit_price: int | None = None
            stop_price: int | None = None

        @dataclass(kw_only=True, frozen=True, slots=True)
        class ModifyOrder(_RequestBase):
            quantity: int
            limit_price: int | None = None
            stop_price: int | None = None

        @dataclass(kw_only=True, frozen=True, slots=True)
        class CancelOrder(_RequestBase):
            pass

    class BrokerResponse:
        @dataclass(kw_only=True, frozen=True, slots=True)
        class _ResponseBase(EventBase):
            internal_order_id: uuid.UUID
            # The broker order ID is carried through the system so that fills and other
            # responses can be reconciled against broker statements. It is optional
            # because some responses (e.g. rejection of a new order) may arrive before
            # the broker has assigned an ID.
            broker_order_id: str | None = None

        @dataclass(kw_only=True, frozen=True, slots=True)
        class CancellationAccepted(_ResponseBase):
            pass

        @dataclass(kw_only=True, frozen=True, slots=True)
        class CancellationRejected(_ResponseBase):
            # Free-form rejection reason as provided by the broker for manual
            # inspection.
            reason: str

        @dataclass(kw_only=True, frozen=True, slots=True)
        class ModificationAccepted(_ResponseBase):
            pass

        @dataclass(kw_only=True, frozen=True, slots=True)
        class ModificationRejected(_ResponseBase):
            reason: str

        @dataclass(kw_only=True, frozen=True, slots=True)
        class OrderAccepted(_ResponseBase):
            pass

        @dataclass(kw_only=True, frozen=True, slots=True)
        class OrderRejected(_ResponseBase):
            reason: str

        # A fill represents a single execution against an order. It does not indicate
        # whether the order is partially or fully filled. The system must track fill
        # quantities internally to determine the remaining open quantity on an order.
        @dataclass(kw_only=True, frozen=True, slots=True)
        class Fill(_ResponseBase):
            internal_fill_id: uuid.UUID
            broker_fill_id: str | None = None
            side: Models.TradeSide
            filled_quantity: int
            fill_price: int
            exchange: str
            # Commission covers all costs associated with this fill (broker fees,
            # exchange fees, regulatory fees, etc.) as a single value.
            commission: int | None = None

        @dataclass(kw_only=True, frozen=True, slots=True)
        class OrderExpired(_ResponseBase):
            pass


# ——————————————————————————————————————————————————————————————————————————————————————
# EVENT BUS DEFINITION
# ——————————————————————————————————————————————————————————————————————————————————————


# The SubscriberLike protocol explicitly documents which methods the EventBus requires
# from its subscribers. This is necessary because EventBus is defined before the
# subscriber base class is defined, so it cannot reference Subscriberbase directly in
# its type annotations.
#
# While `from __future__ import annotations` would also solve the forward reference,
# the protocol makes the contract immediately visible and a reader can see exactly which
# methods the EventBus depends on without having to read through the full Subscriber
# class that is defined below the `EventBus` class.
class SubscriberLike(typing.Protocol):
    def wait_until_idle(self) -> None: ...
    @property
    def is_idle(self) -> bool: ...
    def receive(self, event: EventBase) -> None: ...


class EventBus:
    def __init__(self) -> None:
        # Using a set as the defaultdict's value avoids needing additional logic to
        # guard against duplicate subscriptions in the `add_event_subscription` method.
        self._per_event_subscriptions: defaultdict[
            type[EventBase], set[SubscriberLike]
        ] = defaultdict(set)

        # Because each subscriber in `_per_event_subscriptions` runs in its own thread
        # we need to ensure that `_per_event_subscriptions` can only be accessed from
        # one subscriber thread at a time, for which we need a Lock.
        self._lock: threading.Lock = threading.Lock()

    def add_event_subscription(
        self, subscriber: SubscriberLike, event_type: type[EventBase]
    ) -> None:
        with self._lock:
            self._per_event_subscriptions[event_type].add(subscriber)

    def remove_subscriber(self, subscriber: SubscriberLike) -> None:
        with self._lock:
            for subscriber_set in self._per_event_subscriptions.values():
                subscriber_set.discard(subscriber)

    def publish_event_to_system(self, event: EventBase) -> None:
        # Since the `publish_event_to_system` method is accessed from within the
        # subscriber threads concurrently, we want to minimize the time the Lock is
        # held by each thread so publishing can be done as concurrently as possible
        # between threads. This is why we only copy the set of subscribers for the
        # event type within the Lock and do the rest outside the Lock.
        with self._lock:
            subscribers = self._per_event_subscriptions[type(event)].copy()
        for subscriber in subscribers:
            subscriber.receive(event)

    def wait_until_system_idle(self) -> None:
        # To run backtesting at the maximum possible speed, we want to feed a new piece
        # of market data as soon as the current piece of market data has been completely
        # processed by the system. This is the case when every item that has been put
        # into any of subscribers' internal queue is marked as done via `task_done()`.
        #
        # However, calling each subscriber's `wait_until_idle()` method just once is not
        # sufficient because a subscriber processing its events can publish new events
        # into queues of those subscribers that we have already checked for idleness.
        #
        # This is why after waiting for all subscribers' queues to drain, we need to
        # take a fresh snapshot to verify that every subscriber is still idle.
        # If any subscriber should have become active again, we repeat the process until
        # all of them are truly idle, which is why we need the `while True` loop.
        while True:
            # We only access `_per_event_subscriptions` within the Lock and do the
            # actual waiting outside of it because a subscriber processing its events
            # may publish new events via `publish_event_to_system`, which also needs
            # the Lock.
            #
            # Holding the Lock while waiting would deadlock: the subscriber
            # can't finish processing because it's blocked trying to publish, and we
            # can't stop waiting because the subscriber isn't done.
            with self._lock:
                # The `set().union(*)` deduplicates subscribers that appear under
                # multiple event types so we don't wait on the same subscriber twice.
                subscribers = set().union(*self._per_event_subscriptions.values())
            for subscriber in subscribers:
                subscriber.wait_until_idle()

            with self._lock:
                subscribers = set().union(*self._per_event_subscriptions.values())
            if all(subscriber.is_idle for subscriber in subscribers):
                break


# ——————————————————————————————————————————————————————————————————————————————————————
# GENERAL SYSTEM COMPONENT BASE CLASS DEFINITIONS
# ——————————————————————————————————————————————————————————————————————————————————————

# System components have two fundamental roles: receiving events (subscribing) and
# producing events (emitting). These roles are cleanly separated into `SubscriberBase`
# and `EmitterBase`. Some components only emit (e.g. a data feed), while others both
# subscribe and emit (e.g. a broker).
#
# For structural coherence, and so that both base classes share a single event bus
# reference, they inherit from a common `ComponentBase`. This creates a diamond-like
# inheritance for concrete component base classes that are both emitters and subscribers
# (e.g. `BrokerBase`).
#
#                ComponentBase
#                 /         \
#        SubscriberBase   EmitterBase
#                 \         /    |
#                BrokerBase  DatafeedBase
#
# Additionally, components that interface with external systems (e.g. a broker or data
# feed) use `ExternalComponentMixin` for their connection lifecycle.


class ComponentBase(ABC):
    def __init__(self, event_bus: EventBus) -> None:
        # The concrete `EventBus` instance is injected rather than used as a hard-coded
        # global instance so that in principle, multiple independent systems could
        # co-exist within the same runtime, should this behavior be needed.
        self._event_bus: EventBus = event_bus


class SubscriberBase(ComponentBase):
    def __init__(self, event_bus: EventBus) -> None:
        super().__init__(event_bus)

        # `None` in the type union acts as a poison pill: when the event loop receives
        # `None`, it knows to shut down. See `shutdown` and `_event_loop` methods for
        # how this is implemented.
        self._queue: Queue[EventBase | None] = Queue()

        # `threading.Event` is used instead of e.g. a boolean flag because it is
        # thread-safe and can be checked from any other thread without needing a Lock.
        # We set it before starting the thread so that `receive` can accept events from
        # the moment the thread is alive. Otherwise, the `_running` check in `receive`
        # would fail and events would be silently dropped.
        self._running: threading.Event = threading.Event()
        self._running.set()
        self._thread = threading.Thread(
            target=self._event_loop, name=self.__class__.__name__
        )
        self._thread.start()

    def wait_until_idle(self) -> None:
        # After shutdown, the event loop thread has exited and no longer calls
        # `task_done()`. If an event was placed on the queue right before shutdown,
        # `join()` would block forever waiting for it to be processed. Since a
        # subscriber is idle per definition after shutdown, the method simply returns.
        if not self._running.is_set():
            return
        self._queue.join()

    # The `wait_until_idle` method blocks until the subscriber's queue is joined. This
    # method is a non-blocking (we do not wait for the queue to be empty) check whether
    # the queue is idle.
    @property
    def is_idle(self) -> bool:
        return self._queue.unfinished_tasks == 0

    def receive(self, event: EventBase) -> None:
        if self._running.is_set():
            self._queue.put(event)

    def shutdown(self):
        if not self._running.is_set():
            return
        self._event_bus.remove_subscriber(self)

        # We clear `_running` before putting the poison pill on the queue so that
        # `receive` stops accepting new events before the event loop exits.
        # Otherwise, the event loop could process the poison pill and exit while
        # `receive` is still queuing events that would never be processed.
        self._running.clear()
        self._queue.put(None)

        # A subscriber's `_on_event` handler might call `shutdown()` on itself, in which
        # case we are already inside the subscriber's thread. Calling `join()` on the
        # current thread would deadlock because a thread cannot join itself. This is an
        # explicit guard against such implementation errors.
        if threading.current_thread() is not self._thread:
            self._thread.join()

    def _subscribe_to_events(self, *event_types: type[EventBase]):
        for event_type in event_types:
            self._event_bus.add_event_subscription(self, event_type)

    def _event_loop(self):
        while True:
            event = self._queue.get()

            if event is None:
                # We still need to call `task_done()` for the poison pill itself,
                # otherwise `wait_until_idle` would block forever on `queue.join()`
                # waiting for this unfinished task.
                self._queue.task_done()
                break

            # Subscribers are expected to handle their own exceptions within
            # `_on_event`. This try/except is a last safety net so that an unhandled
            # exception does not crash the subscriber's thread. The exception is
            # delegated to `_on_exception` and the loop continues processing the next
            # event. `task_done()` is in `finally` so the queue's unfinished task count
            # stays correct even when the handler raises.
            try:
                self._on_event(event)
            except Exception as exc:
                self._on_exception(exc)
            finally:
                self._queue.task_done()

    @abstractmethod
    def _on_event(self, event: EventBase):
        pass

    def _on_exception(self, exception: Exception):
        pass


# Each system component can only emit a specific subset of event types. This TypeVar
# is used to parameterize `EmitterBase` so that subclasses specify which event types
# they are allowed to emit via `_emit_event`. This way the type checker enforces the
# restriction without needing to override the method, which would violate the Liskov
# substitution principle.
EmittableEventType = typing.TypeVar("EmittableEventType", bound=EventBase)


# `typing.Generic[EmittableEventType]` makes this class parameterizable so that
# subclasses can specify which event types they are allowed to emit by writing e.g.
# `class DatafeedBase(EmitterBase[SomeMarketUpdateType])`.
class EmitterBase(ComponentBase, typing.Generic[EmittableEventType]):
    # `EmittableEventType` is generic here but gets narrowed to a specific set of event
    # types when a subclass specifies them via `EmitterBase[...]` in its class
    # definition.
    def _emit_event(self, event: EmittableEventType) -> None:
        self._event_bus.publish_event_to_system(event)


# Components that interface with external systems (e.g. a broker or a data feed) need to
# have methods for connecting and disconnecting from external APIs.
class ExternalComponentMixin(ABC):
    @abstractmethod
    def connect(self) -> None:
        pass

    @abstractmethod
    def disconnect(self) -> None:
        pass


# ——————————————————————————————————————————————————————————————————————————————————————
# CONCRETE BASE CLASS DEFINITIONS
# ——————————————————————————————————————————————————————————————————————————————————————


# The `EmitterBase[...]` construction specifies which event types a broker is allowed
# to emit via `_emit_event`. See the `EmittableEventType` TypeVar above for details.
class BrokerBase(
    ExternalComponentMixin,
    SubscriberBase,
    EmitterBase[
        Events.BrokerResponse.OrderAccepted
        | Events.BrokerResponse.OrderRejected
        | Events.BrokerResponse.ModificationAccepted
        | Events.BrokerResponse.ModificationRejected
        | Events.BrokerResponse.CancellationAccepted
        | Events.BrokerResponse.CancellationRejected
        | Events.BrokerResponse.Fill
        | Events.BrokerResponse.OrderExpired
    ],
):
    def __init__(self, event_bus: EventBus):
        super().__init__(event_bus)

        self._subscribe_to_events(
            Events.BrokerRequest.SubmitOrder,
            Events.BrokerRequest.ModifyOrder,
            Events.BrokerRequest.CancelOrder,
        )

    def _on_event(self, event: EventBase) -> None:
        # The parentheses in `SubmitOrder()` et cetera are required by Python's pattern
        # matching. Without them, the name would be treated as a capture pattern that
        # matches any value instead of checking the class.
        match event:
            case Events.BrokerRequest.SubmitOrder() as submit_order_event:
                self._on_submit_order(submit_order_event)
            case Events.BrokerRequest.ModifyOrder() as modify_order_event:
                self._on_modify_order(modify_order_event)
            case Events.BrokerRequest.CancelOrder() as cancel_order_event:
                self._on_cancel_order(cancel_order_event)
            case _:
                return

    @abstractmethod
    def _on_submit_order(self, event: Events.BrokerRequest.SubmitOrder) -> None:
        pass

    @abstractmethod
    def _on_modify_order(self, event: Events.BrokerRequest.ModifyOrder) -> None:
        pass

    @abstractmethod
    def _on_cancel_order(self, event: Events.BrokerRequest.CancelOrder) -> None:
        pass
